This is makeindex, version 2.15 [TeX Live 2016] (kpathsea + Thai support).
Scanning style file ./longer-thesis-chapters.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file longer-thesis-chapters.acn....done (123 entries accepted, 0 rejected).
Sorting entries....done (926 comparisons).
Generating output file longer-thesis-chapters.acr....done (117 lines written, 0 warnings).
Output written in longer-thesis-chapters.acr.
Transcript written in longer-thesis-chapters.alg.
